version: "3.9"

services:
  frontend:
    build: ../frontend
    container_name: rag_frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend

  backend:
    build: ../backend
    container_name: rag_backend
    ports:
      - "4000:4000"
    env_file:
      - ../.env
    environment:
      - PORT=4000
      - INGEST_URL=http://ingest:8000
    depends_on:
      - ingest

  ingest:
    build: ../ingest
    container_name: rag_ingest
    ports:
      - "8000:8000"
    volumes:
      - /data/chroma:/data
    env_file:
      - ../.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - CHROMA_URL=http://chroma:8000
    depends_on:
      - chroma

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/data
