version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: rag_frontend
    ports:
      - "80:80" # 👈 only service exposed publicly
    environment:
      - VITE_API_URL=http://backend:4000
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: rag_backend
    environment:
      - PORT=4000
      - INGEST_URL=http://ingest:8000
    depends_on:
      - ingest

  ingest:
    build: ./ingest
    container_name: rag_ingest
    volumes:
      - /data/chroma:/data # 👈 bind to EBS mount
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - CHROMA_URL=http://chroma:8001
    depends_on:
      - chroma

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: rag_chroma
    volumes:
      - /data/chroma:/data # 👈 same EBS-backed directory
    command: ["--path", "/data", "--host", "0.0.0.0", "--port", "8001"]
#  using host-mounted EBS
